### ISSUE TITLE
Soot / JEI Inscription Stamp issue?

### ISSUE THREAD

**Issue by XIPure** [DaedalusGame/Soot#98] opened 2019-07-04 09:25 UTC
Hi, I was just wondering if there's any way to completely hide/delete all of the stamping recipes in Embers-Rekindled's stamper from JEI when looking up recipes?

[Item] + [Inscription Stamp] = "Renamed Item" for **pretty much every object throughout the game**...... it's so annoying. lol.

I know this has been mentioned before at https://github.com/DaedalusGame/Soot/issues/91 but this doesn't say how to fix the issue, neither does the other issues linked in the comments like Issue(s): 91/1571/90 =(

Is there any type of possible fix assuming it's Soot that's causing this? It's annoying when looking up a recipe and this is _(most of the time)_ the first one that shows which is technically speaking not the right one....!
Like this ME-Drive one for example:
> https://i.imgur.com/AEq8Zw0.jpg
> https://i.imgur.com/lq7fiMi.jpg

Thanks!

P.S - Sorry if this is the wrong section, I just assumed it is the right one, I don't use Github often lol

**Comment by DaedalusGame** [comment] 2019-07-04 10:39
dupe of #90

**Closed by DaedalusGame** 2019-07-04 10:39 UTC

**Comment by XIPure** [comment] 2019-07-04 10:42
@DaedalusGame Hi, that doesn't tell Me how I can fix it. It keeps referencing to other issues. Is there any way what so ever? Please?

**Comment by DaedalusGame** [comment] 2019-07-04 10:51
It's an open issue, which means I need to fix it.

**Comment by XIPure** [comment] 2019-07-04 11:01
@DaedalusGame Ohhh. I see. Sorry for the confusion :p My mistake entirely. I kept thinking it was Embers Rekindled at first but now I don't think it is, as such.

So, do you think it's more than likely Soot that's causing this issue and will a hotfix be posted on the Twitch Launcher?

**Comment by XIPure** [comment] 2019-07-06 12:30
Any updates about this issue if it's possible to fix? Please?
Thanks!

**Comment by XIPure** [comment] 2019-07-12 07:23
Any updates about this issue if it's possible to fix? Please?
Thanks!

@DaedalusGame
