### ISSUE TITLE
Array Index Out of Bounds Error

### ISSUE THREAD

**Issue by ReportBot9009** [DaedalusGame/Soot#88] opened 2019-04-09 03:14 UTC
I'm getting this crash in Project Ozone 3.0.39

java.lang.ArrayIndexOutOfBoundsException: -1

I could have sworn I pasted the crash. sorry...

https://paste.dimdev.org/poxoneragu.mccrash

https://paste.dimdev.org/uqexebemaw.mccrash

https://paste.dimdev.org/siratilipi.mccrash

This happened on a world that I'd been playing for ~20 hours already. I tried to move out of the affected area with each reload of the game, but when I moved far enough away, it would crash immediately on start instead of giving me 5 seconds to fly around. I wish I would have done the /killall command, but I forgot...

I posted this to Abyssalcraft since it was mentioned in one of the crashes on the splash screen (the mod that doesn't kill minecraft and allows you to go back to the front screen).

**Comment by DaedalusGame** [comment] 2019-04-09 10:10
duplicate of #81

**Closed by DaedalusGame** 2019-04-09 10:10 UTC
